from __future__ import annotations

import os
from contextlib import asynccontextmanager
from typing import Literal

from fastapi import FastAPI, HTTPException, Query
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool
from pydantic import BaseModel, Field

DSN = os.getenv("POSTGRES_DSN", "postgresql://fraud:fraud@localhost:5433/fraud")
pool = ConnectionPool(conninfo=DSN, min_size=1, max_size=10, open=False, kwargs={"row_factory": dict_row})

REVIEW_DDL = """
CREATE TABLE IF NOT EXISTS reviewer_decisions (
    transaction_id TEXT PRIMARY KEY REFERENCES fraud_assessments(transaction_id),
    reviewer_id TEXT NOT NULL,
    decision TEXT NOT NULL,
    reason TEXT NOT NULL,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""


class ReviewRequest(BaseModel):
    reviewer_id: str = Field(min_length=2, max_length=100)
    decision: Literal["release", "step_up", "block", "escalate"]
    reason: str = Field(min_length=5, max_length=2000)


@asynccontextmanager
async def lifespan(_: FastAPI):
    pool.open()
    pool.wait()
    with pool.connection() as conn:
        conn.execute(REVIEW_DDL)
        conn.commit()
    yield
    pool.close()


app = FastAPI(
    title="Fraud Streaming Review API",
    version="1.0.0",
    lifespan=lifespan,
    description="Human-review queue over fraud assessments generated by the Kafka streaming scorer.",
)


@app.get("/health")
def health() -> dict[str, str]:
    with pool.connection() as conn:
        conn.execute("SELECT 1").fetchone()
    return {"status": "ok"}


@app.get("/cases")
def list_cases(
    minimum_risk: float = Query(default=0.30, ge=0.0, le=1.0),
    limit: int = Query(default=50, ge=1, le=500),
) -> list[dict]:
    with pool.connection() as conn:
        rows = conn.execute(
            """
            SELECT a.transaction_id, a.customer_id, a.event_time, a.risk_score,
                   a.confidence, a.action, a.signals, a.created_at,
                   d.decision AS reviewer_decision, d.reviewer_id, d.decided_at
            FROM fraud_assessments a
            LEFT JOIN reviewer_decisions d USING (transaction_id)
            WHERE a.risk_score >= %s
            ORDER BY
                CASE WHEN d.transaction_id IS NULL THEN 0 ELSE 1 END,
                a.risk_score DESC,
                a.created_at ASC
            LIMIT %s
            """,
            (minimum_risk, limit),
        ).fetchall()
    return list(rows)


@app.get("/cases/{transaction_id}")
def get_case(transaction_id: str) -> dict:
    with pool.connection() as conn:
        row = conn.execute(
            """
            SELECT a.*, d.decision AS reviewer_decision, d.reason AS reviewer_reason,
                   d.reviewer_id, d.decided_at
            FROM fraud_assessments a
            LEFT JOIN reviewer_decisions d USING (transaction_id)
            WHERE a.transaction_id = %s
            """,
            (transaction_id,),
        ).fetchone()
    if not row:
        raise HTTPException(404, "case not found")
    return row


@app.post("/cases/{transaction_id}/review", status_code=201)
def review_case(transaction_id: str, request: ReviewRequest) -> dict:
    with pool.connection() as conn:
        exists = conn.execute(
            "SELECT 1 FROM fraud_assessments WHERE transaction_id = %s",
            (transaction_id,),
        ).fetchone()
        if not exists:
            raise HTTPException(404, "case not found")
        duplicate = conn.execute(
            "SELECT 1 FROM reviewer_decisions WHERE transaction_id = %s",
            (transaction_id,),
        ).fetchone()
        if duplicate:
            raise HTTPException(409, "case already reviewed")
        row = conn.execute(
            """
            INSERT INTO reviewer_decisions (transaction_id, reviewer_id, decision, reason)
            VALUES (%s, %s, %s, %s)
            RETURNING transaction_id, reviewer_id, decision, reason, decided_at
            """,
            (transaction_id, request.reviewer_id, request.decision, request.reason),
        ).fetchone()
        conn.commit()
    return row


@app.get("/metrics/summary")
def summary() -> dict[str, object]:
    with pool.connection() as conn:
        row = conn.execute(
            """
            SELECT
                COUNT(*) AS assessments,
                COUNT(*) FILTER (WHERE action = 'block_and_review') AS block_review,
                COUNT(*) FILTER (WHERE action = 'step_up_and_review') AS step_up_review,
                ROUND(AVG(risk_score)::numeric, 4) AS mean_risk,
                ROUND(MAX(risk_score)::numeric, 4) AS max_risk
            FROM fraud_assessments
            """
        ).fetchone()
        reviewed = conn.execute("SELECT COUNT(*) AS reviewed FROM reviewer_decisions").fetchone()["reviewed"]
    return {**row, "reviewed": reviewed}
